---
version: '3'

networks:
    conference-app:

services:

  mongo:
    image: mongo:4.2.3
    container_name: mongodb
    networks:
      - conference-app
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
