logging:
    level:
        org.example.conference.events: DEBUG

spring:
    data:
        mongodb:
            authentication-database: admin
            database: event-management
            username: ${DATABASE_USERNAME:root}
            password: ${DATABASE_PASSWORD:example}
            port: ${DATABASE_PORT:27017}
            host: ${DATABASE_HOST:localhost}


